title: Kate Dupon
email: ktdupon@gmail.com
description: >
  I am an experienced UX Designer turned Product Manager, who specializes in
  strategizing, conceptualization, and forming thoughtful, useful, and
  beautiful end-to-end experiences.
baseurl: "" # the subpath of your site, e.g. /blog
cdn: "http://katedupon.com"
url: "http://katedupon.com"
repository: kdupon/kdupon.github.io

assets:
  images: assets/images/
  scripts: assets/js
  styles: assets/css

# Snippet ids
disqus:
  shortname: katedupon

google_analytics: UA-89874612-1

# Custom collections
permalink: pretty
collections:
  recipes:
    output: true

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - README.md
  - node_modules/
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
